### ISSUE TITLE
Love the look of these modules.

### ISSUE THREAD

**Issue by pgatt** [eidetic-av/URack-VCV#1]
Hi there, noticed your modules on a Github crawl. Any chance of them seeing the light of day - currently I can get them to build but they do not show up in VCV.

Billboard alone would be cool and the visuals of the modules is fantastic. Love to be able to play with them all.

**Comment by matth-av** [comment]
Hey! Thanks for checking them out. These modules are not ready for prime-time, but i’m actively working on them.

They’re set to be unveiled at the NIME 2020 conference next month... along with demo videos and instructions on getting started.

I plan on making some posts on the VCV forum and subreddit when that happens. Keep your eyes peeled. I’ll be looking for testers and contributors.
