### ISSUE TITLE
Will not build on Windows!

### ISSUE THREAD

**Issue by caecos** [eidetic-av/URack-VCV#2]
Cannot build on Windows 10 Pro using MSYS64:

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/src/plugin.cpp.o:plugin.cpp:(.rdata$.refptr.modelABBox[.refptr.modelABBox]+0x0): undefined reference to `modelABBox'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/Rack-SDK/compile.mk:59 : plugin.dll] Erreur 1

**Comment by SteveRussell33** [comment]
Comment out the following lines: [no source files for these modules]
https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.hpp#L12 https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.hpp#L14 https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.hpp#L19<br>https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.cpp#L13 https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.cpp#L15 https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/src/plugin.cpp#L20<br>Delete these lines:
https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/plugin.json#L39-L50 https://github.com/eidetic-av/URack-VCV/blob/ed2de7ed396bab2996905af01d5eee0c4c446c6e/plugin.json#L75-L80

**Comment by matth-av** [comment]
Hi, thanks for taking an interest, but these modules can only be used alongside the URack-Player.

I am going to write some documentation on how to get it all working in the coming weeks - and the nature of this repository is changing from a collection of modules to an SDK. I will post on the VCV Rack forum when it is all ready to test out.

For right now, it is not possible to get anything working by just building the modules.

Cheers
